Metrics/AbcSize:
  Max: 45

Metrics/MethodLength:
  Max: 35

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10
