# TODO: Find/improve trouble spots, if possible


Metrics/AbcSize:
  Max: 45

Metrics/MethodLength:
  Max: 35

Metrics/LineLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10